package main;

import java.awt.Color;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.io.*;
import java.net.URI;
import java.net.URISyntaxException;
import javax.swing.JFileChooser;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JSeparator;
import javax.swing.KeyStroke;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author SHADOW
 */
public class main_frame extends javax.swing.JFrame {

    private String path="D:\\PROJET\\VDownloder";
    private String historique_path=null;
    private final String[] command =
	    {
	        "cmd",
	    };
    private final PrintStream printStream;
    PrintWriter stdin;
    
    /**
     * Creates new form main_frame
     */
    public main_frame() {
        initComponents();
        notification.setEnabled(false);
        notification.setDisabledTextColor(Color.black);
        printStream = new PrintStream(new ops(notification));
        System.setOut(printStream);
        System.setErr(printStream);    
        load_files();
        load_historique();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        past = new javax.swing.JPopupMenu();
        Past = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        check_btn = new javax.swing.JButton();
        input = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        notification = new javax.swing.JTextArea();
        download_btn = new javax.swing.JButton();
        number = new javax.swing.JTextField();
        download_btn2 = new javax.swing.JButton();
        check_btn1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        file = new javax.swing.JMenu();
        open = new javax.swing.JMenu();
        historique = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        Exit = new javax.swing.JMenuItem();
        help = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();

        jMenuItem1.setText("jMenuItem1");

        Past.setAccelerator(KeyStroke.getKeyStroke(KeyEvent.VK_V, Toolkit.getDefaultToolkit().getMenuShortcutKeyMask()));
        Past.setText("Past");
        Past.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PastActionPerformed(evt);
            }
        });
        past.add(Past);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 0, 0));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(102, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        check_btn.setBackground(new java.awt.Color(15, 17, 132));
        check_btn.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        check_btn.setForeground(new java.awt.Color(255, 255, 255));
        check_btn.setText("List");
        check_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                check_btnActionPerformed(evt);
            }
        });
        jPanel1.add(check_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 50, 88, 31));

        input.setComponentPopupMenu(past);
        input.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                inputPropertyChange(evt);
            }
        });
        jPanel1.add(input, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 700, 31));

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Video Format  :");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 90, 31));

        notification.setBackground(new java.awt.Color(0, 0, 0));
        notification.setColumns(20);
        notification.setForeground(new java.awt.Color(255, 255, 255));
        notification.setRows(5);
        jScrollPane1.setViewportView(notification);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 88, 700, 250));

        download_btn.setBackground(new java.awt.Color(15, 17, 132));
        download_btn.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        download_btn.setForeground(new java.awt.Color(255, 255, 255));
        download_btn.setText("video");
        download_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                download_btnActionPerformed(evt);
            }
        });
        jPanel1.add(download_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 50, 88, 31));
        jPanel1.add(number, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 110, 30));

        download_btn2.setBackground(new java.awt.Color(15, 17, 132));
        download_btn2.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        download_btn2.setForeground(new java.awt.Color(255, 255, 255));
        download_btn2.setText("Audio");
        download_btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                download_btn2ActionPerformed(evt);
            }
        });
        jPanel1.add(download_btn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 50, 88, 31));

        check_btn1.setBackground(new java.awt.Color(15, 17, 132));
        check_btn1.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        check_btn1.setForeground(new java.awt.Color(255, 255, 255));
        check_btn1.setText("Stop");
        check_btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                check_btn1ActionPerformed(evt);
            }
        });
        jPanel1.add(check_btn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 50, 88, 31));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 350));

        jMenuBar1.setBackground(new java.awt.Color(145, 146, 97));
        jMenuBar1.setForeground(new java.awt.Color(102, 0, 102));
        jMenuBar1.setBorderPainted(false);

        file.setText("File");

        open.setText("Open");
        file.add(open);

        historique.setText("Historique");
        file.add(historique);

        jMenuItem3.setText("Version");
        jMenuItem3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuItem3MousePressed(evt);
            }
        });
        file.add(jMenuItem3);

        Exit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_W, java.awt.event.InputEvent.CTRL_MASK));
        Exit.setText("Exit");
        Exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ExitMousePressed(evt);
            }
        });
        file.add(Exit);

        jMenuBar1.add(file);

        help.setText("Suported site to download");
        help.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                helpMousePressed(evt);
            }
        });
        jMenuBar1.add(help);

        jMenu1.setText("?");
        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(715, 370));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void check_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_check_btnActionPerformed
        load_file();
    }//GEN-LAST:event_check_btnActionPerformed

    private void helpMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_helpMousePressed
        try {
            java.awt.Desktop.getDesktop().browse(new URI("https://ytdl-org.github.io/youtube-dl/supportedsites.html"));
        } catch (IOException | URISyntaxException ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage());
        } 
        
    }//GEN-LAST:event_helpMousePressed

    private void ExitMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitMousePressed
        System.exit(0);
    }//GEN-LAST:event_ExitMousePressed

    private void download_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_download_btnActionPerformed
        if (!input.getText().isEmpty() && !number.getText().isEmpty()) {
            get_vid("-f "+number.getText()+" -c "+input.getText(),true);
        }else if (!input.getText().isEmpty()) {
            get_vid("-F "+input.getText(),false);
        }
    }//GEN-LAST:event_download_btnActionPerformed

    private void download_btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_download_btn2ActionPerformed
        if (!input.getText().isEmpty()) {
            get_vid("-x --audio-format mp3 -c "+input.getText(),true);
        }
    }//GEN-LAST:event_download_btn2ActionPerformed

    private void inputPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_inputPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_inputPropertyChange

    private void PastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PastActionPerformed
        input.paste();
    }//GEN-LAST:event_PastActionPerformed

    private void jMenuItem3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem3MousePressed
        get_vid("--version ", true);
    }//GEN-LAST:event_jMenuItem3MousePressed

    private void check_btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_check_btn1ActionPerformed
        JOptionPane.showMessageDialog(rootPane, "Pas encore implementer");
    }//GEN-LAST:event_check_btn1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main_frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Exit;
    private javax.swing.JMenuItem Past;
    private javax.swing.JButton check_btn;
    private javax.swing.JButton check_btn1;
    private javax.swing.JButton download_btn;
    private javax.swing.JButton download_btn2;
    private javax.swing.JMenu file;
    private javax.swing.JMenu help;
    private javax.swing.JMenu historique;
    private javax.swing.JTextField input;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea notification;
    private javax.swing.JTextField number;
    private javax.swing.JMenu open;
    private javax.swing.JPopupMenu past;
    // End of variables declaration//GEN-END:variables

    private void get_vid(String text, boolean par1) {
        notification.setText("");
        if(par1) save_historique(input.getText());
        Thread t = new Thread(new Runnable() {
            @Override
            public void run() {
                Process p;
                try {
                    p = Runtime.getRuntime().exec(command);
                    new Thread(new SyncPipe(p.getErrorStream(), System.err)).start();
                    new Thread(new SyncPipe(p.getInputStream(), System.out)).start();
                    stdin = new PrintWriter(p.getOutputStream());
                    stdin.println("cd "+path);
                    stdin.println(path+"\\youtube-dl "+text);
                    stdin.close();
                    p.waitFor();
                } catch (IOException | InterruptedException e) {
                    JOptionPane.showMessageDialog(rootPane, e.getMessage());
                }
            }
        });
            t.start(); 
    }

    private void load_files() {
        open.removeAll();
        File f=new File(path);
        File[] files=f.listFiles();
        
        JMenuItem m = new JMenuItem("Open Folder");
        m.addMouseListener(new MouseListener() {
            @Override
            public void mouseClicked(MouseEvent e) {}
            @Override
            public void mousePressed(MouseEvent e) {
                try {
                        java.awt.Desktop.getDesktop().open(f);
                    } catch (IOException ex) {
                        JOptionPane.showMessageDialog(rootPane, f.getName()+" Could not be opened :"+ex.getMessage());
                    }
            }
            @Override
            public void mouseReleased(MouseEvent e) {}
            @Override
            public void mouseEntered(MouseEvent e) {}
            @Override
            public void mouseExited(MouseEvent e) {}
        });
        m.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));  
        
        open.add(m);        
        
        for (File file1 : files) {
            m = new JMenuItem(file1.getName());            
            m.addMouseListener(new MouseListener() {
                @Override
                public void mouseClicked(MouseEvent e) {}
                @Override
                public void mousePressed(MouseEvent e) {
                    try {
                        java.awt.Desktop.getDesktop().open(file1);
                    } catch (IOException ex) {
                        JOptionPane.showMessageDialog(rootPane, file1.getName()+" Could not be opened");
                    }
                }
                @Override
                public void mouseReleased(MouseEvent e) {}
                @Override
                public void mouseEntered(MouseEvent e) {}
                @Override
                public void mouseExited(MouseEvent e) {}
            });
            if (file1.isDirectory()) {
                m.setBackground(Color.YELLOW);
                m.setForeground(new java.awt.Color(230,140,0));
            } 
            open.add(m);
        }
        
        m = new JMenuItem("Change defult derectory");
        m.addMouseListener(new MouseListener() {
            @Override
            public void mouseClicked(MouseEvent e) {}
            @Override
            public void mousePressed(MouseEvent e) {
                //change_path_option();
            }
            @Override
            public void mouseReleased(MouseEvent e) {}
            @Override
            public void mouseEntered(MouseEvent e) {}
            @Override
            public void mouseExited(MouseEvent e) {}
        });
        m.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_MASK));
        open.add(new JSeparator());
        open.add(m);
    }

    private void load_file() {
        if (!input.getText().isEmpty()) {
            get_vid("-a "+input.getText(),true);
        }else{
            JFileChooser r=new JFileChooser();
            r.setCurrentDirectory(r.getFileSystemView().getHomeDirectory());
            r.setFileSelectionMode(JFileChooser.FILES_ONLY);
            r.addChoosableFileFilter(new FileNameExtensionFilter("Text", "txt"));
            r.setAcceptAllFileFilterUsed(true);
            int result = r.showOpenDialog(this);
            if (result == JFileChooser.APPROVE_OPTION) {
                input.setText(r.getSelectedFile().getAbsolutePath());
                get_vid("-a "+r.getSelectedFile().getAbsolutePath(),true);
            }
        }
    }

    private void load_historique() {
        File f=new File(System.getProperty("user.home"),"Documents");
        File f2=new File (f.getAbsoluteFile()+"/VDownloder");
        File f3=new File (f.getAbsoluteFile()+"/VDownloder/temp.txt");
        historique_path=f3.getAbsolutePath();
        if(!f2.exists()){
            f2.mkdirs();
        }
        if(!f3.exists()){
            try {
                f3.createNewFile();
            } catch (IOException e) {
                System.out.println("can't create file");
            }
        }
        try {
            BufferedReader fr=new BufferedReader(new FileReader(f3));
            String st;
            int i=0;
            JMenuItem m;
            while((st=fr.readLine())!=null && i<10){
                if(st.length()>0){
                    m = new JMenuItem(st);
                    m.addMouseListener(new MouseListener() {
                        @Override
                        public void mouseClicked(MouseEvent e) {}
                        @Override
                        public void mousePressed(MouseEvent e) {
                        }
                        @Override
                        public void mouseReleased(MouseEvent e) {}
                        @Override
                        public void mouseEntered(MouseEvent e) {}
                        @Override
                        public void mouseExited(MouseEvent e) {}
                    });
                    historique.add(m);
                }
            }
        } catch (IOException e) {
            JOptionPane.showMessageDialog(rootPane,"Erruer :"+e.getLocalizedMessage());
        }
    }

    private void save_historique(String text) {
        if(historique_path!=null){
            File f3=new File (historique_path);
            if(!f3.exists()){
                load_historique();
            }
            try {
                BufferedWriter fw=new BufferedWriter(new FileWriter(historique_path,true));
                fw.newLine();
                fw.write(text);
                fw.close();
                load_historique();
            } catch (IOException e) {
                JOptionPane.showMessageDialog(rootPane,"Erruer :"+e.getLocalizedMessage());
            }
        }
    }
}
